# TODO: when real images are added, store or resolve them by each location's image_key.

LOCATIONS = [
    {
        "id": "airplane",
        "name_ru": "Самолёт",
        "name_en": "Airplane",
        "image_key": "airplane",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "bank",
        "name_ru": "Банк",
        "name_en": "Bank",
        "image_key": "bank",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "beach",
        "name_ru": "Пляж",
        "name_en": "Beach",
        "image_key": "beach",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "broadway_theater",
        "name_ru": "Бродвейский театр",
        "name_en": "Broadway Theater",
        "image_key": "broadway_theater",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "casino",
        "name_ru": "Казино",
        "name_en": "Casino",
        "image_key": "casino",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "cathedral",
        "name_ru": "Собор",
        "name_en": "Cathedral",
        "image_key": "cathedral",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "circus_tent",
        "name_ru": "Цирковой шатёр",
        "name_en": "Circus Tent",
        "image_key": "circus_tent",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "corporate_party",
        "name_ru": "Корпоративная вечеринка",
        "name_en": "Corporate Party",
        "image_key": "corporate_party",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "crusader_army",
        "name_ru": "Армия крестоносцев",
        "name_en": "Crusader Army",
        "image_key": "crusader_army",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "day_spa",
        "name_ru": "Спа-салон",
        "name_en": "Day Spa",
        "image_key": "day_spa",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "embassy",
        "name_ru": "Посольство",
        "name_en": "Embassy",
        "image_key": "embassy",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "hospital",
        "name_ru": "Больница",
        "name_en": "Hospital",
        "image_key": "hospital",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "hotel",
        "name_ru": "Отель",
        "name_en": "Hotel",
        "image_key": "hotel",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "military_base",
        "name_ru": "Военная база",
        "name_en": "Military Base",
        "image_key": "military_base",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "movie_studio",
        "name_ru": "Киностудия",
        "name_en": "Movie Studio",
        "image_key": "movie_studio",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "ocean_liner",
        "name_ru": "Океанский лайнер",
        "name_en": "Ocean Liner",
        "image_key": "ocean_liner",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "passenger_train",
        "name_ru": "Пассажирский поезд",
        "name_en": "Passenger Train",
        "image_key": "passenger_train",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "pirate_ship",
        "name_ru": "Пиратский корабль",
        "name_en": "Pirate Ship",
        "image_key": "pirate_ship",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "polar_station",
        "name_ru": "Полярная станция",
        "name_en": "Polar Station",
        "image_key": "polar_station",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "police_station",
        "name_ru": "Полицейский участок",
        "name_en": "Police Station",
        "image_key": "police_station",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "restaurant",
        "name_ru": "Ресторан",
        "name_en": "Restaurant",
        "image_key": "restaurant",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "school",
        "name_ru": "Школа",
        "name_en": "School",
        "image_key": "school",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "service_station",
        "name_ru": "Автозаправка",
        "name_en": "Service Station",
        "image_key": "service_station",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "space_station",
        "name_ru": "Космическая станция",
        "name_en": "Space Station",
        "image_key": "space_station",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "submarine",
        "name_ru": "Подводная лодка",
        "name_en": "Submarine",
        "image_key": "submarine",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "supermarket",
        "name_ru": "Супермаркет",
        "name_en": "Supermarket",
        "image_key": "supermarket",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "university",
        "name_ru": "Университет",
        "name_en": "University",
        "image_key": "university",
        "set": "spyfall_1",
        "enabled_by_default": True,
    },
    {
        "id": "amusement_park",
        "name_ru": "Парк аттракционов",
        "name_en": "Amusement Park",
        "image_key": "amusement_park",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "art_museum",
        "name_ru": "Художественный музей",
        "name_en": "Art Museum",
        "image_key": "art_museum",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "candy_factory",
        "name_ru": "Кондитерская фабрика",
        "name_en": "Candy Factory",
        "image_key": "candy_factory",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "cat_show",
        "name_ru": "Выставка кошек",
        "name_en": "Cat Show",
        "image_key": "cat_show",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "cemetery",
        "name_ru": "Кладбище",
        "name_en": "Cemetery",
        "image_key": "cemetery",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "coal_mine",
        "name_ru": "Угольная шахта",
        "name_en": "Coal Mine",
        "image_key": "coal_mine",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "construction_site",
        "name_ru": "Стройплощадка",
        "name_en": "Construction Site",
        "image_key": "construction_site",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "gaming_convention",
        "name_ru": "Игровой фестиваль",
        "name_en": "Gaming Convention",
        "image_key": "gaming_convention",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "gas_station",
        "name_ru": "Бензоколонка",
        "name_en": "Gas Station",
        "image_key": "gas_station",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "harbor_docks",
        "name_ru": "Портовые доки",
        "name_en": "Harbor Docks",
        "image_key": "harbor_docks",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "ice_hockey_stadium",
        "name_ru": "Хоккейный стадион",
        "name_en": "Ice Hockey Stadium",
        "image_key": "ice_hockey_stadium",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "jail",
        "name_ru": "Тюрьма",
        "name_en": "Jail",
        "image_key": "jail",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "jazz_club",
        "name_ru": "Джаз-клуб",
        "name_en": "Jazz Club",
        "image_key": "jazz_club",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "library",
        "name_ru": "Библиотека",
        "name_en": "Library",
        "image_key": "library",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "night_club",
        "name_ru": "Ночной клуб",
        "name_en": "Night Club",
        "image_key": "night_club",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "race_track",
        "name_ru": "Ипподром",
        "name_en": "Race Track",
        "image_key": "race_track",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "retirement_home",
        "name_ru": "Дом престарелых",
        "name_en": "Retirement Home",
        "image_key": "retirement_home",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "rock_concert",
        "name_ru": "Рок-концерт",
        "name_en": "Rock Concert",
        "image_key": "rock_concert",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "sightseeing_bus",
        "name_ru": "Экскурсионный автобус",
        "name_en": "Sightseeing Bus",
        "image_key": "sightseeing_bus",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "stadium",
        "name_ru": "Стадион",
        "name_en": "Stadium",
        "image_key": "stadium",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "subway",
        "name_ru": "Метро",
        "name_en": "Subway",
        "image_key": "subway",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "the_un",
        "name_ru": "ООН",
        "name_en": "The U.N.",
        "image_key": "the_un",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "vineyard",
        "name_ru": "Виноградник",
        "name_en": "Vineyard",
        "image_key": "vineyard",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "wedding",
        "name_ru": "Свадьба",
        "name_en": "Wedding",
        "image_key": "wedding",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
    {
        "id": "zoo",
        "name_ru": "Зоопарк",
        "name_en": "Zoo",
        "image_key": "zoo",
        "set": "spyfall_2",
        "enabled_by_default": False,
    },
]
