LOCATIONS = [
    {"id": "airport", "name_ru": "Аэропорт", "name_en": "Airport", "image_key": "airport"},
    {"id": "amusement_park", "name_ru": "Парк аттракционов", "name_en": "Amusement Park", "image_key": "amusement_park"},
    {"id": "bank", "name_ru": "Банк", "name_en": "Bank", "image_key": "bank"},
    {"id": "beach", "name_ru": "Пляж", "name_en": "Beach", "image_key": "beach"},
    {"id": "casino", "name_ru": "Казино", "name_en": "Casino", "image_key": "casino"},
    {"id": "cathedral", "name_ru": "Собор", "name_en": "Cathedral", "image_key": "cathedral"},
    {"id": "circus_tent", "name_ru": "Цирковой шатёр", "name_en": "Circus Tent", "image_key": "circus_tent"},
    {"id": "corporate_office", "name_ru": "Офис компании", "name_en": "Corporate Office", "image_key": "corporate_office"},
    {"id": "cruise_ship", "name_ru": "Круизный лайнер", "name_en": "Cruise Ship", "image_key": "cruise_ship"},
    {"id": "embassy", "name_ru": "Посольство", "name_en": "Embassy", "image_key": "embassy"},
    {"id": "hospital", "name_ru": "Больница", "name_en": "Hospital", "image_key": "hospital"},
    {"id": "hotel", "name_ru": "Отель", "name_en": "Hotel", "image_key": "hotel"},
    {"id": "library", "name_ru": "Библиотека", "name_en": "Library", "image_key": "library"},
    {"id": "movie_studio", "name_ru": "Киностудия", "name_en": "Movie Studio", "image_key": "movie_studio"},
    {"id": "museum", "name_ru": "Музей", "name_en": "Museum", "image_key": "museum"},
    {"id": "nightclub", "name_ru": "Ночной клуб", "name_en": "Nightclub", "image_key": "nightclub"},
    {"id": "ocean_liner", "name_ru": "Океанский лайнер", "name_en": "Ocean Liner", "image_key": "ocean_liner"},
    {"id": "police_station", "name_ru": "Полицейский участок", "name_en": "Police Station", "image_key": "police_station"},
    {"id": "restaurant", "name_ru": "Ресторан", "name_en": "Restaurant", "image_key": "restaurant"},
    {"id": "school", "name_ru": "Школа", "name_en": "School", "image_key": "school"},
    {"id": "space_station", "name_ru": "Космическая станция", "name_en": "Space Station", "image_key": "space_station"},
    {"id": "submarine", "name_ru": "Подводная лодка", "name_en": "Submarine", "image_key": "submarine"},
    {"id": "supermarket", "name_ru": "Супермаркет", "name_en": "Supermarket", "image_key": "supermarket"},
    {"id": "theater", "name_ru": "Театр", "name_en": "Theater", "image_key": "theater"},
    {"id": "university", "name_ru": "Университет", "name_en": "University", "image_key": "university"},
    {"id": "zoo", "name_ru": "Зоопарк", "name_en": "Zoo", "image_key": "zoo"},
]
